<?php
/**
 * show flashMessages - with Style!
 */

if (array_key_exists('error', $this->msgs) && sizeof($this->msgs['error']) > 0) {
    ?>
    <div class="alert alert-error">
        <a class="close" data-dismiss="alert" href="#">×</a>
        <?php
        foreach ($this->msgs['error'] as $message) {
            echo $message;
        }
        ?>
    </div>
    <?php
}

if (array_key_exists('warning', $this->msgs) && sizeof($this->msgs['warning']) > 0) {
    ?>
    <div class="alert">
        <a class="close" data-dismiss="alert" href="#">×</a>
        <?php
        foreach ($this->msgs['warning'] as $message) {
            echo $message;
        }
        ?>
    </div>
    <?php
}

if (array_key_exists('success', $this->msgs) && sizeof($this->msgs['success']) > 0) {
    ?>
    <div class="alert alert-success">
        <a class="close" data-dismiss="alert" href="#">×</a>
        <?php
        foreach ($this->msgs['success'] as $message) {
            echo $message;
        }
        ?>
    </div>
    <?php
}

if (array_key_exists('info', $this->msgs) && sizeof($this->msgs['info']) > 0) {
    ?>
    <div class="alert alert-info">
        <a class="close" data-dismiss="alert" href="#">×</a>
        <?php
        foreach ($this->msgs['info'] as $message) {
            echo $message ;
        }
        ?>
    </div>
    <?php
}
?>