<?php if ($this->canCreate):
         $params = isset($this->actionParams['create']) ? $this->actionParams['create'] : array();
?>
<a class="btn" href="<?php echo $this->url(array_merge(array('module' => $this->module, 'controller' => $this->controller, 'action' => 'create'), $params), 'default', true)?>">
    <i class="icon-plus"></i> <?php echo isset($this->createEntityText) ? $this->translate($this->createEntityText) : $this->translate('New %1$s', $this->translate($this->entityTitle)) ?></a>
<?php endif; ?><br /><br />