<?php echo $this->doctype(); ?>
<html lang="en">
  <head>
    <title>
        <?php
        if (!is_null($this->pageTitle)) {
            echo $this->pageTitle;
        } else {
            echo "Testomat";
        };
        ?>
    </title>

    <?php echo $this->headMeta(); ?>  
    
    <!-- Le styles -->
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <?php echo $this->headScript(); ?>
    
    <!-- Le fav and touch icons -->
    <!--
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    -->
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->LayoutGetHomeLink(); ?>">Testomat</a>
          
          <div class="btn-group pull-right">
            <?php echo $this->LayoutLoggedInAs(); ?>
          </div>
          
          <div class="nav-collapse">
                <?php
                $partial = array('partials/topMenu.phtml', 'default');
                $this->navigation()->menu()->setPartial($partial);
                echo $this->navigation()->menu()->render();
                ?>
          </div>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <?php 
        /**
        *@todo: change layout of breadcrumbs 
        */
        $partial = array('partials/breadCrumbs.phtml', 'default');
        $this->navigation()->breadcrumbs()->setPartial($partial);
        echo $this->navigation()->breadcrumbs()->setMinDepth(0)->render();
      ?>
      
      <?php
        /**
         *@todo: change layout of flash messages 
         */
        echo $this->partial('partials/flashMessages.phtml', array('msgs' => $this->LayoutGetFlashMessages()));
      ?>

      <?php echo $this->layout()->content; ?>
      
      <hr />

      <footer>
        <p>&copy; Sandy Lewanscheck 2012 / Questions? Contact <a href="mailto:<?= $this->emailSupport ?>"><?= $this->emailSupport ?></a></p>
      </footer>

    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <?php echo $this->inlineScript(); ?>

  </body>
</html>