<?php echo $this->doctype() ?>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>
        <?php
        if (!is_null($this->pageTitle)) {
            echo $this->pageTitle;
        } else {
            echo "Plotomat";
        };
        ?>
    </title>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
<?php echo $this->headScript(); ?>
</head>
<body>
    <div class="topbar">
        <div class="topbar-inner">
            <div class="container-fluid">
                <a class="brand" href="<?php echo $this->LayoutGetHomeLink(); ?>">Plotomat</a>

                <?php
                $partial = array('partials/topMenu.phtml', 'default');
                $this->navigation()->menu()->setPartial($partial);
                echo $this->navigation()->menu()->render();
                ?>

                <p class="pull-right"><?php echo $this->LayoutLoggedInAs(); ?></p>

            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div><?php echo $this->navigation()->breadcrumbs()->setMinDepth(0)->render(); ?></div>
        <div class="content">

            <?php
            echo $this->partial('partials/flashMessages.phtml', array('msgs' => $this->LayoutGetFlashMessages()));
            ?>

<?php echo $this->layout()->content; ?>

            <footer>
                <p>&copy; Sandy Lewanscheck 2012 / Questions? Contact <a href="mailto:<?= $this->emailSupport ?>"><?= $this->emailSupport ?></a></p>

            </footer>
        </div>
    </div>

</body>
</html>