<form id="frm" method="POST">
	<fieldset>
		<legend>Enter new user</legend>
		
		<div class="clearfix">
			<label for="name">username:</label>
			<div class="input">
			<input type="text" name="username" id="username" value="<?= $this->username; ?>" /> 
			</div>
		</div>
		
		<div class="clearfix">
			<label for="email">email:</label>
			<div class="input">
			<input type="text" name="email" id="email" value="<?= $this->email; ?>" />
			</div> 
		</div>
		
		<div class="clearfix">
			<label for="aclRole">role:</label>
			<div class="input">
			<select id="aclRole" class="medium" name="aclRole">
                <option value="">---</option>
                <?php foreach ($this->aclRoles as $role): ?>
					<option value="<?php echo $role->id; ?>"
					<?php if($role->id == $this->role_id) echo 'selected="selected"'; ?>
					>
						<?php echo $role->name; ?>
					</option>
				<?php endforeach; ?>
			</select>
			</div> 
		</div>
		
		<div class="actions">
			<input type="submit" name="btsubmit" id="btsubmit" value="submit" />
		</div>
	</fieldset>  	
</form>