<?php if ($this->pageCount > 1): ?>
<div class="zs-pager">
<!-- First page link -->
<?php if ($this->current != $this->first): ?>
<a href="<?php echo $this->url(array('module' => $this->module, 
									'controller' => $this->controller,
									'action' => $this->action,
									'page' => $this->first),'pagination') ?>" class="first">&lt;&lt;</a>
<?php endif; ?>
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
<a href="<?php echo $this->url(array('module' => $this->module, 
									'controller' => $this->controller,
									'action' => $this->action,
									'page' => $this->previous),'pagination') ?>" class="previous">&lt;</a>&nbsp;
<?php endif; ?>
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
<a href="<?php echo $this->url(array('module' => $this->module, 
									'controller' => $this->controller,
									'action' => $this->action,
									'page' => $page),'pagination') ?>"><?php echo $page; ?></a>
  <?php else: ?>
<span class="select"><?php echo $page ?></span>
  <?php endif; ?>
<?php endforeach; ?>
<!-- Next page link -->
<?php if (isset($this->next)): ?>
&nbsp;<a href="<?php echo $this->url(array('module' => $this->module, 
									'controller' => $this->controller,
									'action' => $this->action,
									'page' => $this->next),'pagination') ?>" class="next">&gt;</a>
<?php endif; ?>
<!-- Last page link -->
<?php if ($this->current != $this->last): ?>
<a href="<?php echo $this->url(array('module' => $this->module, 
									'controller' => $this->controller,
									'action' => $this->action,
									'page' => $this->last),'pagination') ?>" class="last">&gt;&gt;</a>
<?php endif; ?>
</div>
<?php endif; ?>